RES = {
    "accidents": [],
    "brand": "BMW",
    "color": "FEKETE",
    "engine_size": 4398,
    "first_reg": "1998.10.15.",
    "first_reg_hun": "1998.10.15.",
    "fuel_type": "BENZIN",
    "gearbox": "Automata",
    "status": "A jármű forgalomban van",
    "type_code": "740 I",
    "year": 1998,
    "model": "",
    "num_of_owners": 5,
    "performance": 281,
    "restrictions": [],
    "mileage": [],
    # "inspections": [],
}
